FROM node:22-alpine

WORKDIR /app
RUN npm install -g pnpm

COPY packages/lavender-data-ui/package.json packages/lavender-data-ui/package.json
COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .
COPY tsconfig.json .
COPY .eslintrc.json .
COPY .prettierrc .
COPY .prettierignore .

WORKDIR /app/packages/lavender-data-ui
RUN pnpm install

COPY packages/lavender-data-ui .
RUN pnpm build

CMD ["pnpm", "start"]