name: Tests

on:
  push:
    branches: [main]
    paths:
      - 'packages/lavender-data-docs/**'
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Build docs
        run: |
          cd packages/lavender-data-docs
          pnpm i
          pnpm build

      - name: Deploy docs
        run: |
          aws s3 sync ./packages/lavender-data-docs/dist s3://${{ secrets.AWS_S3_DOCS_BUCKET }}/ --delete
