name: Tests

on:
  push:
    branches: [main, release/*]
    paths:
      - 'packages/lavender-data/**'
  pull_request:
    branches: [main, release/*]
    paths:
      - 'packages/lavender-data/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bookworm

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.8.5'

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: packages/lavender-data/.venv
          key: lavender-data-venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl

          cd packages/lavender-data
          poetry install --no-interaction
          # tensor serialization tests
          poetry run pip install torch --index-url https://download.pytorch.org/whl/cpu
          # s3 storage tests
          poetry run pip install boto3 tqdm
          # converter tests
          poetry run pip install webdataset pillow

      - name: Run tests
        run: |
          cd packages/lavender-data
          poetry run python -m unittest discover -s tests -p 'test_*.py'
        env:
          LAVENDER_DATA_MODULES_DIR: ''
